/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:52:50 GMT 2018
 */

package com.cts.application.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.exceptions.FileExceptionWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileExceptionWrapper_ESTest extends FileExceptionWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper("0HoK_\"vq@*CtId&'f?8");
      String string0 = fileExceptionWrapper0.toString();
      assertEquals("0HoK_\"vq@*CtId&'f?8", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper("");
      String string0 = fileExceptionWrapper0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper();
      String string0 = fileExceptionWrapper0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper("0HoK_\"vq@*CtId&'f?8");
      String string0 = fileExceptionWrapper0.getMessage();
      assertEquals("0HoK_\"vq@*CtId&'f?8", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper("");
      String string0 = fileExceptionWrapper0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FileExceptionWrapper fileExceptionWrapper0 = new FileExceptionWrapper();
      String string0 = fileExceptionWrapper0.toString();
      assertNull(string0);
  }
}
