/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:53:03 GMT 2018
 */

package com.cts.application.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.utils.FileConstants;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileConstants_ESTest extends FileConstants_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileConstants fileConstants0 = new FileConstants();
  }
}
