/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 14 22:40:36 GMT 2018
 */

package com.cts.application.model.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.model.xml.Record;
import com.cts.application.model.xml.Records;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecordsTest extends RecordsTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Records records0 = new Records();
      LinkedList<Record> linkedList0 = new LinkedList<Record>();
      records0.setRecords(linkedList0);
      List<Record> list0 = records0.getRecords();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Records records0 = new Records();
      LinkedList<Record> linkedList0 = new LinkedList<Record>();
      Record record0 = new Record();
      linkedList0.add(record0);
      records0.setRecords(linkedList0);
      List<Record> list0 = records0.getRecords();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Records records0 = new Records();
      List<Record> list0 = records0.getRecords();
      assertNull(list0);
  }
}
