/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 14 22:42:38 GMT 2018
 */

package com.cts.application.model.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.model.xml.Record;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecordTest extends RecordTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal((-4687L));
      record0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getStartBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal(2648);
      record0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getStartBalance();
      assertEquals((short)2648, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Record record0 = new Record();
      Integer integer0 = new Integer(1126);
      record0.setReference(integer0);
      Integer integer1 = record0.getReference();
      assertEquals(1126, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Record record0 = new Record();
      Integer integer0 = new Integer((-1861));
      record0.setReference(integer0);
      Integer integer1 = record0.getReference();
      assertEquals((-1861), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      record0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getMutation();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal((-476L));
      record0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getMutation();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal(3475L);
      record0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getMutation();
      assertEquals((short)3475, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal(0L);
      record0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getEndBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      record0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getEndBalance();
      assertEquals((short)10, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Record record0 = new Record();
      record0.setDescription("a1?_n |>lJ-c>^]! }");
      String string0 = record0.getDescription();
      assertEquals("a1?_n |>lJ-c>^]! }", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Record record0 = new Record();
      record0.setAccountNumber(", End Balance = ");
      String string0 = record0.getAccountNumber();
      assertEquals(", End Balance = ", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Record record0 = new Record();
      record0.setAccountNumber("");
      String string0 = record0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = record0.getStartBalance();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Record record0 = new Record();
      String string0 = record0.toString();
      assertEquals("Customer Statement Record: [Transaction Reference = null, Account Number = null, Description = null, Start Balance = null, Mutation = null, End Balance = null]", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Record record0 = new Record();
      Integer integer0 = record0.getReference();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Record record0 = new Record();
      record0.setDescription("");
      String string0 = record0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = record0.getMutation();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Record record0 = new Record();
      String string0 = record0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal((-1.0));
      record0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getEndBalance();
      assertEquals((byte) (-1), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = new BigDecimal(0);
      record0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = record0.getStartBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Record record0 = new Record();
      BigDecimal bigDecimal0 = record0.getEndBalance();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Record record0 = new Record();
      String string0 = record0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Record record0 = new Record();
      Integer integer0 = new Integer(0);
      record0.setReference(integer0);
      Integer integer1 = record0.getReference();
      assertEquals(0, (int)integer1);
  }
}
