/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:52:38 GMT 2018
 */

package com.cts.application.model.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.model.csv.CustomerStatementRecord;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomerStatementRecord_ESTest extends CustomerStatementRecord_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer(281);
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals(281, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer(0);
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer((-2279));
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals((-2279), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer((-1));
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal(2899);
      customerStatementRecord0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getStartBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-1807.703047));
      customerStatementRecord0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getStartBalance();
      assertEquals((short) (-1807), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertEquals((short)1, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-2563.110012));
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-1807.703047));
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setDescription("o*f9[w^6%9X!pp+b");
      String string0 = customerStatementRecord0.getDescription();
      assertEquals("o*f9[w^6%9X!pp+b", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setDescription("");
      String string0 = customerStatementRecord0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setAccountNumber("3xRiv<`nS1j4Uc~[49|");
      String string0 = customerStatementRecord0.getAccountNumber();
      assertEquals("3xRiv<`nS1j4Uc~[49|", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setAccountNumber("");
      String string0 = customerStatementRecord0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = customerStatementRecord0.getTransactionRef();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      customerStatementRecord0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getStartBalance();
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getStartBalance();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getMutation();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.toString();
      assertEquals("Customer Statement Record: [Transaction Reference = null, Account Number = null, Description = null, Start Balance = null, Mutation = null, End Balance = null]", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getEndBalance();
      assertNull(bigDecimal0);
  }
}
