/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 14 22:41:57 GMT 2018
 */

package com.cts.application.model.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.model.csv.CustomerStatementRecord;
import java.math.BigDecimal;
import java.math.MathContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomerStatementRecordTest extends CustomerStatementRecordTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer((-725));
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals((-725), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer(3461);
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals(3461, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      MathContext mathContext0 = MathContext.DECIMAL64;
      BigDecimal bigDecimal1 = bigDecimal0.remainder(bigDecimal0, mathContext0);
      customerStatementRecord0.setStartBalance(bigDecimal1);
      BigDecimal bigDecimal2 = customerStatementRecord0.getStartBalance();
      assertSame(bigDecimal2, bigDecimal1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal(3850);
      customerStatementRecord0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getStartBalance();
      assertEquals((short)3850, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-284.5359134761));
      customerStatementRecord0.setStartBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getStartBalance();
      assertEquals((byte) (-28), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertEquals((byte)1, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-1573L));
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertEquals((short) (-1573), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = new BigDecimal((-15.9));
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertEquals((byte) (-15), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setDescription("JE8bT[Qw[h!h-");
      String string0 = customerStatementRecord0.getDescription();
      assertEquals("JE8bT[Qw[h!h-", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setDescription("");
      String string0 = customerStatementRecord0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setAccountNumber(", End Balance = ");
      String string0 = customerStatementRecord0.getAccountNumber();
      assertEquals(", End Balance = ", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      customerStatementRecord0.setAccountNumber("");
      String string0 = customerStatementRecord0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      customerStatementRecord0.setMutation(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getMutation();
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = new Integer((byte)0);
      customerStatementRecord0.setTransactionRef(integer0);
      Integer integer1 = customerStatementRecord0.getTransactionRef();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      Integer integer0 = customerStatementRecord0.getTransactionRef();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getStartBalance();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getMutation();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      customerStatementRecord0.setEndBalance(bigDecimal0);
      BigDecimal bigDecimal1 = customerStatementRecord0.getEndBalance();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      String string0 = customerStatementRecord0.toString();
      assertEquals("Customer Statement Record: [Transaction Reference = null, Account Number = null, Description = null, Start Balance = null, Mutation = null, End Balance = null]", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CustomerStatementRecord customerStatementRecord0 = new CustomerStatementRecord();
      BigDecimal bigDecimal0 = customerStatementRecord0.getEndBalance();
      assertNull(bigDecimal0);
  }
}
