/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:52:17 GMT 2018
 */

package com.cts.application;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.AppConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AppConfig_ESTest extends AppConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AppConfig appConfig0 = new AppConfig();
      Jaxb2Marshaller jaxb2Marshaller0 = appConfig0.getCastorMarshaller();
      assertNull(jaxb2Marshaller0.getContextPath());
  }
}
