/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 28 14:52:17 GMT 2018
 */

package com.cts.application;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AppConfig_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.cts.application.AppConfig"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\470679\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "D:\\Thiru\\Important\\Cognizant\\RaboBank\\WIP\\CodeAssignment"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\470679"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "470679"); 
    java.lang.System.setProperty("user.timezone", "Asia/Calcutta"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AppConfig_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.oxm.mime.MimeUnmarshaller",
      "org.springframework.oxm.ValidationFailureException",
      "org.springframework.oxm.jaxb.Jaxb2Marshaller",
      "org.springframework.beans.factory.Aware",
      "org.springframework.oxm.Unmarshaller",
      "org.springframework.beans.factory.InitializingBean",
      "org.springframework.oxm.Marshaller",
      "org.springframework.oxm.jaxb.Jaxb2Marshaller$Jaxb2AttachmentMarshaller",
      "org.springframework.oxm.GenericUnmarshaller",
      "com.cts.application.model.xml.Records",
      "com.cts.application.AppConfig",
      "org.springframework.oxm.UncategorizedMappingException",
      "org.springframework.core.NestedExceptionUtils",
      "org.springframework.oxm.UnmarshallingFailureException",
      "org.springframework.core.io.Resource",
      "org.springframework.oxm.MarshallingException",
      "org.springframework.core.NestedRuntimeException",
      "org.springframework.oxm.MarshallingFailureException",
      "org.springframework.core.io.ResourceLoader",
      "org.springframework.oxm.jaxb.Jaxb2Marshaller$Jaxb2AttachmentUnmarshaller",
      "org.springframework.util.ObjectUtils",
      "org.springframework.context.ResourceLoaderAware",
      "org.springframework.oxm.GenericMarshaller",
      "org.springframework.beans.factory.annotation.Autowire",
      "org.springframework.context.annotation.Configuration",
      "org.springframework.oxm.XmlMappingException",
      "org.springframework.oxm.mime.MimeMarshaller",
      "org.springframework.stereotype.Component",
      "org.springframework.oxm.mime.MimeContainer",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.beans.factory.BeanClassLoaderAware",
      "org.springframework.util.Assert"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AppConfig_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.cts.application.AppConfig",
      "org.springframework.beans.factory.annotation.Autowire",
      "org.springframework.oxm.jaxb.Jaxb2Marshaller",
      "org.springframework.util.Assert",
      "org.springframework.util.ObjectUtils"
    );
  }
}
