/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:50:02 GMT 2018
 */

package com.cts.application;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cts.application.AssignmentApplication;
import com.cts.application.service.FileHelperService;
import com.cts.application.service.FileProcessorService;
import com.cts.application.service.RecordHelperService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AssignmentApplication_ESTest extends AssignmentApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AssignmentApplication assignmentApplication0 = new AssignmentApplication();
      String[] stringArray0 = new String[0];
      try { 
        assignmentApplication0.run(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cts.application.AssignmentApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      AssignmentApplication.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "http://www.w3.org/2001/XMLSchema";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("application.yml");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "http://www.w3.org/2001/XMLSchema");
      stringArray0[1] = "org.springframework.core.NestedIOException";
      stringArray0[2] = "]Kmrm4";
      stringArray0[3] = "org.springframework.oxm.jaxb.Jaxb2Marshaller";
      stringArray0[4] = "file";
      stringArray0[5] = "";
      stringArray0[6] = "r#me-F,AED}E.5Xdm{6";
      stringArray0[7] = "";
      stringArray0[8] = "(H$fuDDx?NI";
      // Undeclared exception!
      try { 
        AssignmentApplication.main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Failed to load property source from location 'file:./application.yml'
         //
         verifyException("org.springframework.boot.context.config.ConfigFileApplicationListener$Loader", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        AssignmentApplication.main((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Args must not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[9];
      // Undeclared exception!
      try { 
        AssignmentApplication.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.core.env.SimpleCommandLineArgsParser", e);
      }
  }
}
