/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:48:59 GMT 2018
 */

package com.cts.application.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cts.application.service.FileHelperService;
import com.cts.application.service.FileProcessorService;
import com.cts.application.service.RecordHelperService;
import java.io.File;
import java.nio.file.InvalidPathException;
import java.nio.file.NoSuchFileException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.PathResource;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileHelperService_ESTest extends FileHelperService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      MockFile mockFile0 = new MockFile("");
      String string0 = fileHelperService0.getFullFileName(mockFile0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileExtension((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileExtension("org.springframework.oxm.MarshallingFailureException");
      assertEquals("MarshallingFailureException", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileBaseName((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileBaseName("file");
      assertEquals("file", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      File file0 = fileHelperService0.createFailedReportFile(".", ".");
      assertEquals("._1392409281320..", file0.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      // Undeclared exception!
      try { 
        fileHelperService0.processFiles((List<File>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cts.application.service.FileHelperService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      // Undeclared exception!
      try { 
        fileHelperService0.getResource("/)u1geS_2l<9o2g");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      // Undeclared exception!
      try { 
        fileHelperService0.getFullFileName((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cts.application.service.FileHelperService", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      try { 
        fileHelperService0.collectFiles("file");
        fail("Expecting exception: NoSuchFileException");
      
      } catch(NoSuchFileException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      // Undeclared exception!
      try { 
        fileHelperService0.collectFiles("`i2'c[RJ.E!|6!");
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      // Undeclared exception!
      try { 
        fileHelperService0.collectFiles((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      LinkedList<File> linkedList0 = new LinkedList<File>();
      int int0 = fileHelperService0.processFiles(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      PathResource pathResource0 = new PathResource("");
      File file0 = pathResource0.getFile();
      String string0 = fileHelperService0.getResourceType(file0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("fwDk#\\fwDk#");
      FileSystemHandling.createFolder(evoSuiteFile0);
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      MockFile mockFile0 = new MockFile("fwDk#", "fwDk#");
      String string0 = fileHelperService0.getResourceType(mockFile0);
      assertEquals("directory", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      MockFile mockFile0 = new MockFile("org.springframework.oxm.MarshallingFailureException", "org.springframework.oxm.MarshallingFailureException");
      String string0 = fileHelperService0.getResourceType(mockFile0);
      assertNotNull(string0);
      assertEquals("file", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getResourceType((File) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileExtension("`");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = new FileProcessorService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "fileHelperService", (Object) fileHelperService0);
      Jaxb2Marshaller jaxb2Marshaller0 = new Jaxb2Marshaller();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "jaxb2Marshaller", (Object) jaxb2Marshaller0);
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Injector.inject(fileProcessorService0, (Class<?>) FileProcessorService.class, "recordHelperService", (Object) recordHelperService0);
      Injector.validateBean(fileProcessorService0, (Class<?>) FileProcessorService.class);
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      File file0 = fileHelperService0.getResource("");
      assertEquals(0L, file0.lastModified());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      FileHelperService fileHelperService0 = new FileHelperService();
      FileProcessorService fileProcessorService0 = mock(FileProcessorService.class, new ViolatedAssumptionAnswer());
      Injector.inject(fileHelperService0, (Class<?>) FileHelperService.class, "fileProcessorService", (Object) fileProcessorService0);
      Injector.validateBean(fileHelperService0, (Class<?>) FileHelperService.class);
      String string0 = fileHelperService0.getFileBaseName("");
      assertEquals("", string0);
  }
}
