/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 14:50:55 GMT 2018
 */

package com.cts.application.service;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cts.application.service.RecordHelperService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecordHelperService_ESTest extends RecordHelperService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Boolean boolean0 = recordHelperService0.isFieldValid("3");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Boolean boolean0 = recordHelperService0.isFieldValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RecordHelperService recordHelperService0 = new RecordHelperService();
      Boolean boolean0 = recordHelperService0.isFieldValid((String) null);
      assertFalse(boolean0);
  }
}
